#!/bin/bash
UND="\033[0;4m"
NC="\033[0;0m"
DG="\033[1;30m"
IT="\033[0;3m"
LB="\033[1;34m"
RD="\033[0;31m"
BK="\033[1;6m"
echo ""
echo -e "Welcome to the$RD CrowdStrike Falcon$NC sensor deployment automation demonstration!"
echo ""
figlet -w 220 -f smslant Demo Commands
echo -e "-------------------------------------------------------------------------------"
echo -e "| Please note: All sensor installations leverage AWS Systems Manager packages |"
echo -e "-------------------------------------------------------------------------------"
echo -e "| agent-install         - Installs the Falcon Sensor to an instance remotely  |"
echo -e "| agent-uninstall       - Removes the Falcon Sensor from an instance remotely |"
echo -e "| connect               - Connect to a Windows or Linux instance.             |"
echo -e "| list-agents           - List current agent installation status on instances |"
echo -e "| list-instances        - List all available instances in the demonstration   |"
echo -e "| local-agent-install   - Install the Falcon Sensor locally                   |"
echo -e "| local-agent-uninstall - Remove the local Falcon Sensor                      |"
echo -e "| show-code             - Show the source code for any of these commands      |"
echo -e "-------------------------------------------------------------------------------"

